### ISSUE TITLE
Need help with this if possible

### ISSUE THREAD

**Issue by xremmy** [Fruitfella/ROBOT-binary#103]
Hello Fruifella,
I am trying to combine compounding with martingale. It compounds, but when the loss comes and it martingales, it does not revert back to the initial stake. It starts using the martingale stake to trade.
![fruitfella question 4](https://user-images.githubusercontent.com/25975068/31797696-952d5126-b527-11e7-8dcc-fb9fd14055ce.JPG)

PS; I saw you started a script to do this type of function in your tools page, but its not available there. Want to know if its possible or the binary logic wont allow it. 
Thank you.

**Comment by xremmy** [comment]
Also, if its possible to put the number of times it should compound before returning to initial stake
example: compound 5 times, revert to initial stake. if loss happens, then martingale 2 times then revert to initial stake.

**Comment by Fruitfella** [comment]
I made martingale+compound management months ago, but dunno why i don't want to share it 😛 
maybe because it took too much time and effort (and got a lot of headaches) to developed it, or maybe i just being stingy 😆 

okay, i'll just give you some hints..
- count every wins in a row
- if it loss after a win, set the stake to initial stake
- if after wins in row reached the target (5 times), set the stake to initial stake

**Comment by xremmy** [comment]
Thanks Fruitfella for the suggestions, will try and see if i can get it right.
And you are very right to keep on to some of the tools you developed, you have already shared a lot freely here. And you are still on hand to help, that's something most people wont do.
But then, **Fruitfella** is a special one.

Thanks again and God bless.

**Comment by Fruitfella** [comment]
:)
bless you too

**Comment by xremmy** [comment]
Hello Fruitfella, 
Finally cracked it. Thanks for making me use the head. Interesting process of drawing the flowchart. had to do the basics.
