### ISSUE TITLE
Help wanted with Martingale

### ISSUE THREAD

**Issue by dune2** [Fruitfella/ROBOT-binary#11]
Hello Sir, I wanted to know how to put Martingale amounts as
under instead of using multiplayer if possible:

Start with 0.5
then 1.1
then 2.3
then 4.8
then 10.2 etc.

Thank You!

**Comment by Fruitfella** [comment]
hi @dune2 , idk why i didnt get notification from github to my email anymore, didnt know u came here XP.
there are many martingale formula out there, and all of them using multiplier. Its just that they use it differently.
here r some of them : 
new stake = last stake x multiplier
new stake = last stake + (last stake x multiplier) 
new stake = last profit x multiplier
new stake = last stake + (last profit x multiplier)

idk how u get that number, i cant see their relation at all. 
try to experiment with those formula. and remember that multiplier isnt always "2".
for example, i use the 4th formula and "1.1" as my multiplier.
to define ur multiplier, u should think how did u get that number, what number is the "factor" that make ur stake increase that way. that "factor" is ur multiplier.

**Comment by dune2** [comment]
Thank you for reply Sir! 
I will try your suggestions! 
As for how I arrive at those numbers, I will explain:
By using Multiplier x we only get profit till level 4 of martingale, level 5 and higher levels get us negative return!
![regularmartingale](https://cloud.githubusercontent.com/assets/28773865/26337986/345320d0-3f96-11e7-99b1-70c4eeea5c5e.jpg)
That is why I want to use manually entered levels to get constant profit no matter which level it is!
![manualmartingale](https://cloud.githubusercontent.com/assets/28773865/26338033/7df85110-3f96-11e7-9d7a-24350a1f6aca.jpg)

**Comment by Fruitfella** [comment]
woah, u risk more than $350? thats a lot.
anyway u should try the 2nd formula **new stake = last stake + (last stake x multiplier)**
for multiplier use "1.1" or "1.2". im to lazy to calculate the result, but i believe with that formula u can always get positive return. the multiplier is depend on the return percentage of the contract.
u know that some contracts has more than 100% return while other has 96%, 94% and theres even 9% return.
idk which martingale xml u use, so cant give u the exact sample.
this is how u put that formula to block
_change_ **stake** _by_ **stake x 1.1**
so use "change" instead of "set" block in menu **Advanced** -> **Variable**

**Comment by dune2** [comment]
Thank You Sir, for your wonderful support! While trying out your suggestions, I succeeded in making my Martingale! 

 
![manualmartingaledone](https://cloud.githubusercontent.com/assets/28773865/26415082/b07673c6-40ca-11e7-8873-3c2f4dc4d958.jpg)

**Comment by Fruitfella** [comment]
Congrats 👍
