### ISSUE TITLE
HELP....ONLY CROSS, SMA 1 X SMA2

### ISSUE THREAD

**Issue by ubanemas** [Fruitfella/ROBOT-binary#6]
HI FRUITFELLA.....can you helpme about this....
i try to make only if sma 1 cross sma 2 then purchase rise/fall
but my bot is purchase more, like 2 3 or more purchase
how the solution, maybe you can give me for example thanks......

**Comment by Fruitfella** [comment]
@ubanemas more detail please..
like SMAs setting/parameters and trade duration, itd be better if u could show me ur bot that has this problem. so that i dont need to build it from scratch and not to mention that what i thought about MAs crossing doesnt necessarily same with yours.

**Comment by ubanemas** [comment]
trade duration i use 5 minutes

**Comment by ubanemas** [comment]
![t 1](https://cloud.githubusercontent.com/assets/27851415/26031672/9c65b378-38a6-11e7-938e-90782d707055.jpg)
need help....

**Comment by Fruitfella** [comment]
for MAs crosses, its hard to use candle list since there are 4 data in 1 candle (high,low,open,close) while MA need 1 data (close/median/weight/etc). if u want to candle list anyway, u should make a list of only 1 data like 'close' for example.
dunno why i cant attach a pic now. i got this error 'Something went really wrong, and we can’t process that file. Try again.'

about how to make a list?
_Set_ **list** _to_ **|** _create list with_ **[** _Read_ [Close] _in_ [1] _recent candle_ **]**
---------- **|** --------------- **[** _Read_ [Close] _in_ [2] _recent candle_ **]**
---------- **|** --------------- **[** _Read_ [Close] _in_ [3] _recent candle_ **]**
---------- **|** --------------- **[** _Read_ [Close] _in_ [4] _recent candle_ **]**
---------- **|** --------------- **[** _Read_ [Close] _in_ [5] _recent candle_ **]**

do note that on MA, Period cant be less than Input list. so if u want to make a 50 periods SMA, u need at least make a list of 51 recent candles.

**Comment by Fruitfella** [comment]
@ubanemas my previous post is a bit complicated but it can be use for many possibilities of MA crosses and for trend forecast.
as for purchase once when MA cross each other, this simple example can do it fine.
![max](https://cloud.githubusercontent.com/assets/26277327/26037545/3ff76bf8-391f-11e7-8827-894f7ba19bf1.PNG)

**Comment by Fruitfella** [comment]
after u set variables SMA10 and SMA50 (use the variable **list** above as input list)
this is how to do 1x purchase when SMA10 x SMA50.
![max](https://cloud.githubusercontent.com/assets/26277327/26037621/343b00d4-3921-11e7-8a36-1079f0015f76.PNG)

**Comment by ubanemas** [comment]
![set sma 1](https://cloud.githubusercontent.com/assets/27851415/26039851/b7af0582-3949-11e7-95e7-48979454966a.jpg)
![set sma 2](https://cloud.githubusercontent.com/assets/27851415/26039850/b7aeeb9c-3949-11e7-8d9c-f2de714c17a0.jpg)
![set sma3](https://cloud.githubusercontent.com/assets/27851415/26039852/b7b4d6c4-3949-11e7-932c-96270b5ded52.jpg)
still not work, why maybe something mis???

**Comment by ubanemas** [comment]
![ok](https://cloud.githubusercontent.com/assets/27851415/26040399/28413586-394f-11e7-96da-c9db4f2bbb2d.jpg)
![ok2](https://cloud.githubusercontent.com/assets/27851415/26040400/2845c0ba-394f-11e7-9673-0ceeae07283d.jpg)
![ok3](https://cloud.githubusercontent.com/assets/27851415/26040401/285c812e-394f-11e7-9b72-89b8b13f3574.jpg)
if like this can op, but not cross, only if sma 1 higher or lower then purchase

**Comment by Fruitfella** [comment]
input candle on SMA should be **list** not **candle list**
![smax](https://cloud.githubusercontent.com/assets/26277327/26045754/df8a6bc4-3975-11e7-937f-99df4757f3bd.png)

**Comment by Fruitfella** [comment]
im still testing my bot that seem got error after i made some changes, so i cant test this SMAs cross. Logically its should work.

**Comment by ubanemas** [comment]
![1](https://cloud.githubusercontent.com/assets/27851415/26084947/5dad915e-3a0a-11e7-90d0-b127a2da2e2a.jpg)
![2](https://cloud.githubusercontent.com/assets/27851415/26084946/5d9c9516-3a0a-11e7-856a-bb5f24220da6.jpg)

**Comment by Fruitfella** [comment]
@ubanemas dont use SMA Array, use normal SMA instead.

**Comment by Fruitfella** [comment]
btw udah check vanilla comunity? #8
dsana banyak coder & dev, banyak juga yg bagi2 strategy sama bot. cuma aq baru liat sekilas masih belum nongkrong dsna. @ubanemas

**Comment by Fruitfella** [comment]
i just noticed that some of ur blocks are disabled (grey), right click on it -> _Enable block_, to enable it.

**Comment by Fruitfella** [comment]
@ubanemas i just noticed that some of ur blocks are disabled (grey), right click on it -> Enable block, to enable it.

**Comment by ubanemas** [comment]
otw #8
