### ISSUE TITLE
Rise Fall Tick Trend Bot Help

### ISSUE THREAD

**Issue by mnaseem01** [Fruitfella/ROBOT-binary#60]
Hi @Fruitfella .
I am trying to use your functions. it's running very fine for few times and getting good profit, suddenly suck all balance lost and lost. I don't know why it is. I lost today around $200.
Need help how to fix this if market going strange, slapping, or against. 
1. Tick Trade trend showing only Down or UP. It is possible we can add No Change or No Trend At least we save the profit.
2. What is best settings for This Tick Trend, Period and Candle List times. 
3- Please recommend this best time frame (e.g 5 ticks, 1 M, etc)
Thanks alot you are always help me alot..

![image](https://user-images.githubusercontent.com/13481811/29242240-64584834-7f9a-11e7-89dc-44c66b44806a.png)

**Comment by Fruitfella** [comment]
Dude, those functions are just tools, dont use it as it is, but use it with your own strategy.
That trend function only tell you the trend direction, it doesnt tell you when to purchase.
1. there is actually _flat trend_ , i dont put it into a block because it doesnt needed, no one would take action when there is no trend. if you want to use it, you simply use **Logic** _if_ , like : 
_if_ **`trend is up`**
_do_ **somethings**
_else if_ **`trend is down`**
_.......do_ **somethings**
_else_ **somethings**
2. there is no _best settings_ , 14 is the most common. this function made of _moving averages_ , so its depend on what period you usually use MA for trend signal.
3. use **`Ticks List`** as input if you trades in ticks duration, use **candle close list** if you trades in minutes duration or higher.

p.s. actually, i use trend signal as _filter_ for most strategies, that means i only purchase **Call** when trend is Up, of course in _reversal_ strategies i purchase **Call** when trend is Down.

**Comment by mnaseem01** [comment]
@Fruitfella , thanks alot, i got i will do it the same.

**Comment by NetworkerTrader007** [comment]
@Fruitfella Buenas Noches estaba viendo estos bots y veo que eres experto en la materia...
Nose si me puedes ayudar con el siguiente bots...
como hago para tener la lectura de los ultimos ticks si van arriba o abajo..
La estartegia que quiero aplicar es la siguiente..3 ticks arriba Purchase FAll y si 3 ticks abajo Purchase Rise...mas o menos igual al algoritmo que tienes con las 3 velas del mismo color..pero yo quiero con ticks...podria ser posible?...

**Comment by pierhans** [comment]
@Fruitfella hi, do you have a rise/fall bot for sale ?

**Comment by Fruitfella** [comment]
@pierhans you're too late dude. i sold some bots last year.
now, i have nothing for sale.
i still have some bots, but currently still under development. not safely profitable yet.
i'll contact you if its done. but don't hope too much, as i don't focus on making bots anymore and only do it on my spare time.

**Comment by pierhans** [comment]
@Fruitfella Thanks, I appreciate it

**Comment by Somina007** [comment]
@Fruitfella please do you have any rise fall bots for sale?

**Comment by Guterez** [comment]
Hi, can somebody help me how to make instructions in my Rise Fall bot
1. When candle is green and 4 ticks go down in a row (the spot is red - red - red - red ) purchase rise
2. When candle is red and 4 ticks go up in a row (the spot is blue - blue - blue - blue) purchase fall
I have tried to do like this:
If ... is candle black ... (bla bla bla) = false
  do ... If tick1 < tick2 and tick2 < tick3 and tick3 < tick4
             do ... Purchase Rise
But it doesn't work
I know nothing about making bot script just trying to modify bots free-downloaded from youtube.
Would be very happy if someone can help me solve this issue for me.
Many thanks in advance
