### ISSUE TITLE
Help to solve the problem

### ISSUE THREAD

**Issue by Daler4ik** [Fruitfella/ROBOT-binary#63]
I want to make sure that the robot sets when the last decimal number is 1, and after a while again 1, and the purchase is different.

I ask to forgive me for my English, I'm using Google translator :(

**Comment by Fruitfella** [comment]
do you mean last digit? try this @Daler4ik 
![capture](https://user-images.githubusercontent.com/26277327/29451310-6429f29a-842c-11e7-8b05-320da3bdde22.png)

it will work like this : 
1 ->waiting
2
5
8
1 ->purchase different
3
7
2
8
4
1->waiting
1->purchase different
9
5

good luck

**Comment by Daler4ik** [comment]
Thank you very much. Now I'll try and unsubscribe :) :) :) :)

**Comment by Daler4ik** [comment]
@Fruitfella Thank you again. Everything is working)

**Comment by Fruitfella** [comment]
👍  😄

**Comment by Daler4ik** [comment]
@Fruitfella Excuse me, could you help us with something else? I have a bot that trades at higher / lower, the problem is that, the barrier is only exposed in +, is it possible to make so that the purchase below the barrier was "-", the purchase of the above barrier was "+"?

**Comment by Fruitfella** [comment]
yes and no, thats depend on your strategy.
i dont recommend you to do that though, its better to just choose 1 type of purchase.

**Comment by Daler4ik** [comment]
@Fruitfella You probably misunderstood me. When the bot opens the deal on the up, a barrier with a plus. When the bot opens the deal on the down, the barrier also has a plus. Is it possible to do so so that when there is a bet on the drop, the barrier is with a minus?

(I apologize for my terrible English)

**Comment by Fruitfella** [comment]
i get your point, thats why i said its depend on your strategy.
- if you want to **change the barrier after analyzing** then you can't do that. (NO)
- but if you just want to **change the barrier after a trade**, that is possible. (YES)

example : 
- if the candle is green you want to purchase higher (+) and if candle is red you want to purchase lower(-), this is a **NO**, you can't change the barrier.
- if after a loss of purchase higher (+) you want to switch purchase lower (-). this is an **OK**, you can do that.

the reason is because the system in binary bot, we must define the contract detail first in main block (1) before we could start analyzing the market and applying strategies in main block (2), and all the main blocks are processed successively from main block (1), (2), (3) and (4).

p.s. main block are those 4 blue blocks with number on it
p.s. don't worry about your english, perhaps my english is worse than yours 😜

**Comment by Daler4ik** [comment]
@Fruitfella I understood everything, thank you. You have helped me a lot, God grant you well-being)
