### ISSUE TITLE
Anyone with a bot that has minimum lose

### ISSUE THREAD

**Issue by Agentsbu** [Fruitfella/ROBOT-binary#93]
Hi Guys, Does anyone have a bot that have minimal risk level. For example : doesn't higher than 7 martingale level ? Even if it's for Sale. My budget is 100 USD.

**Comment by xremmy** [comment]
Hello Agentsbu, i don't think anyone with a truly profitable bot would want to sell it or make it public. Except for the marketers with "how i made $1000 in 30minutes" banner. 
I have some bots i am testing and trying to fine-tune using some of Fruitfella's tools, can send it to you but only privately. You can check it out and possibly see other ways of improving it which I'm not seeing

**Comment by Jo-Hans** [comment]
I do have a bot that never exceed martingale level 7 (i tested it for 1 full month), in fact it rarely touch that level. of course i don't want to share it, but if somebody want to buy it, i will consider it. someone told me it is okay to share/sell the bot as long as the users aren't too many. so, selling it to 1-2 ppl is okay i think.
the problem is i can't guarantee that my bot will never-ever exceed that martingale level. you know that sometimes lags happen right? caused by processing delays and network delays. this lag might cause 1 or 2 losses, and if this lag were to happen when we already get 5-6 consecutive losses, you know what will happen..
that is why i am a bit hesitate :(

**Comment by Agentsbu** [comment]
@Jo-hans here is my email. Brothershongwe@gmail.com

**Comment by Agentsbu** [comment]
@xremmy use my email. brothershonwe@mail.com

**Comment by Agentsbu** [comment]
@xremmy still waiting.

**Comment by xremmy** [comment]
@Agentsbu sent. you gave me wrong email.

**Comment by Agentsbu** [comment]
@Xremmy the email address is brothershongwe@gmail.com

**Comment by Fruitfella** [comment]
@Agentsbu someone gave me a bot and said that you want me to check it before you buy it?

**Comment by Agentsbu** [comment]
Yes @Fruitfella I want to check if the bot can meet the requirement. if  doesn't get higher than 7 martingale level.

**Comment by Fruitfella** [comment]
I've checked the bot @Agentsbu 
here are my conclusions : 
- It use a legit technical analysis (_he asked me to keep the detail secret_)
- The duration is 57 seconds. it aim for 1 minute candle per trade
- It was built by me, so there is no problem with the coding. Its work according to the strategy.
- Tested it for about 12 hours start at 22.00 server time (05.00 my time), the max loss level (martingale level) is 5, and its only happen once.
- There was strong trends, flat trends and even some choppy trends. so i'm sure that the performance is okay since different trends didn't affect the bot that much. too bad i fail to check at what trend did it get loss lv5. i already closed the tab before saving the log ;P
- The chance it will get loss lv7 is rare*

*note : if you are just unlucky and get some processing delays or network delays while purchasing a contract and you already get 5 consecutive losses, you might get loss lv7 or even higher (very very rare), depends on how severe those delays are. but this is not the strategy's nor the coding's fault ;p

**Comment by Agentsbu** [comment]
Dude this is incredible. for the fact that you tested the system and even technical analysis of it. m flattered. I will get back to him for purchasing the bot.

**Comment by Agentsbu** [comment]
@Fruitfella. you must contact me private to get a tip. just tell me how much you want for rour work. It's unfair to put you to work all the time for free. i am hoping for some long term business with you.

**Comment by Fruitfella** [comment]
@Agentsbu actually i don't do all this for money, but i'm open for donations and tips 😄 
i'll contact you now, make sure you have fasapay.com account or else better forget it, as i don't have any other online payment account and bank transfer is kinda troublesome (and take times) :)

**Comment by baruga** [comment]
ada nggak ya yang bisa membantu membuatkan bot binary RF dengan lose seminimal mungkin..

**Comment by baruga** [comment]
@Agentsbu I have a bot with my strategy, maybe that's what you are looking for the bot.

**Comment by Agentsbu** [comment]
Hi @baruga can you please email me brothershongwe@gmail.com.

**Comment by Agentsbu** [comment]
Hi @fruitfella fasapay is troublesome. I use skrill, paypal, webmoney or bank transfer

**Comment by baruga** [comment]
Hi @Jo-Hans can sent me your emails pls...

**Comment by Jo-Hans** [comment]
@baruga what for?

**Comment by baruga** [comment]
@Jo-Hans there i want to ask about the bot you created

**Comment by Jo-Hans** [comment]
okay, give me your email, i'll contact you.

**Comment by baruga** [comment]
@Jo-Hans my email nusantaraaditama@gmail.com

**Comment by Jo-Hans** [comment]
walah, org indo toh. ribet pake bhs kampung haha

**Comment by Jo-Hans** [comment]
udah q kontak, cek email.

**Comment by baruga** [comment]
@Jo-Hans yo wes ben mas seklian belajar bahasa sebelah

**Comment by Aloyjoe** [comment]
please you guys should help me write my strategy on binarybot or if you have a profitable bot you can give me email kamsochi@gmail.com

**Comment by baruga** [comment]
@Aloyjoe ?????
